services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: dataplatform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d dataplatform" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"
      - "9001:9001" # MinIO Console
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped



  app:
    build:
      context: .
    volumes:
      - type: bind
        source: ./utils
        target: /app/utils
      - type: bind
        source: ./data
        target: /app/data
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespassword@postgres-db:5432/dataplatform
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  postgres-data:
  minio-data:


